# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a36cd22b15c4e320cfa1359418d586cf7b35c00679287cb3ce52b07a0bc1ce4f7779581405afe280ed4ccfd307592073886dd912ad664d35ebfb684492f99054

test:
  secret_key_base: 34616741c33090ad67a30a1e7aaec0ed1745d69f91447839a2e0e2c36067d972d91a8fcf7304491452a1853b1402160bc5025158102a4af5aa853f8abf774871

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
